// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhrsfmwhlrbvpsorqeoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRocnNmbXdobHJidnBzb3JxZW96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzQwNTcsImV4cCI6MjA3MTMxMDA1N30.Ec1XQgLdL1eTx1e7TI4yajDpk2AXxGnPwPJov8b5uSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});